---
- name: Importing python script
  ansible.builtin.script: files/pull_orb_from_mdm.py {{ client_id }} {{ client_secret }}
  args:
    executable: python3
  register: orb_list_output
  ignore_errors: true
  changed_when: false

- name: Formatting ORB list
  ansible.builtin.set_fact:
    orb_list: "{{ orb_list_output.stdout_lines[0] }}"
  failed_when: false

- name: Display the output
  loop: "{{ orb_list }}"
  ansible.builtin.debug:
    msg: "{{ item }}"

- name: Adding ORB into IRM
  loop: "{{ orb_list }}"
  irm.irm.irm_device:
    irm_token: "{{ irm_token }}"
    irm_url: "{{ irm_url }}"
    data:
      site: "{{ item.store_id | lower }}"
      name: "{{ 'orb-' + item.store_id | lower + '-' + item.orb_number }}"
      custom_fields:
        device_id: "{{ item.device_id }}"
      device_type:
        id: 13
      device_role:
        id: 12
    validate_certs: false
