---
- name: Obtain MDM access token
  ansible.builtin.uri:
    url: "{{ generate_mdm_token_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: client_credentials
      client_id: "{{ generate_mdm_token_client_id }}"
      client_secret: "{{ generate_mdm_token_client_secret }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: auth_response

- name: Check for HTTP errors
  ansible.builtin.fail:
    msg: "Failed to obtain access token"
  when: auth_response.status != 200

- name: Set access token and headers
  ansible.builtin.set_fact:
    access_token: "{{ auth_response.json.access_token }}"
    headers:
      Authorization: "Bearer {{ auth_response.json.access_token }}"
      Accept: "application/json;version=2"
      Content-Type: "application/json"

- name: Pull down ipads from MDM
  ansible.builtin.uri:
    url: "{{ mdm_devices_url }}"
    method: GET
    validate_certs: false
    return_content: true
    headers: "{{ headers }}"
  register: device_list

- name: Add ipads to IRM
  loop: "{{ device_list.json.Devices }}"
  irm.irm.irm_device:
    irm_token: "{{ irm_token }}"
    irm_url: "{{ irm_url }}"
    data:
      site: "{{ item.UserName }}"
      name: "{{ item.DeviceFriendlyName }}"
      device_type:
        id: 1
      device_role: restaurant-tech
      serial: "{{ item.SerialNumber }}"
      asset_tag: "{{ item.DeviceId }}"
    validate_certs: false
