---
- name: Importing python script
  ansible.builtin.script: files/pull_pos_from_mdm.py {{ client_id }} {{ client_secret }}
  args:
    executable: python3
  register: pos_list_output
  ignore_errors: true
  changed_when: false

- name: Formatting POS list
  ansible.builtin.set_fact:
    pos_list: "{{ pos_list_output.stdout_lines[0] }}"
  failed_when: false

- name: Display the output
  loop: "{{ pos_list }}"
  ansible.builtin.debug:
    msg: "{{ item }}"

- name: Adding POS into IRM
  loop: "{{ pos_list }}"
  irm.irm.irm_device:
    irm_token: "{{ irm_token }}"
    irm_url: "{{ irm_url }}"
    data:
      site: "{{ item.store_id | lower }}"
      name: "{{ 'pos-' + item.store_id | lower + '-' + item.pos_number }}"
      custom_fields:
        device_id: "{{ item.device_id }}"
      device_type:
        id: 11
      device_role:
        id: 10
    validate_certs: false
